### PR TITLE
Provide image loading state in MetaImage via a publisher

### PR DESCRIPTION
**Pull request by npresseault**
## Description
We expose a publisher with image loading state. Initial state is `none` and then it is updated to `success` for local image or `success`/`error` with remote images.

## Motivation and Context
Using the onSuccess / onError publishers in the image flow, it is possible to provide alternate images to load. There was no way, however, to know wether the global image was loaded or not.

Using that technique, we're now able to take action on images errors by showing an alternate view for instance.

## How Has This Been Tested?
Tested with images being loaded from network and not being loaded. Tested with local images.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jdtremblay** [comment]
I don't like setting a global state to drive other behavior that loading the image. Why don't you map the onError externally to bind the external view you need?

**Comment by martingagnon** [comment]
Sample project in https://github.com/mirego/trikot.metaviews/tree/master/sample should also be updated to explain the behaviour.

**Comment by npresseault** [comment]
@jdtremblay 
`onError` can be used to provide an alternate ImageFlow which indicates a way to get alternate image. This is not my use case.

My use case is that I have another meta view (a MetaLabel) which I want to show in case the MetaImage was not loaded properly.

If that is possible with `onError`, please provide me an example.

**Comment by marcantoinefortier** [comment]
> I don't like setting a global state to drive other behavior that loading the image. 

I have the same concern. Could we opt for a "wrapper-style" solution instead?

**Comment by npresseault** [comment]
Care to elaborate on "wrapper-style" solution?

FYI and sorry that was not clarified ealier, but I had offline talk with @jdtremblay on the topic and exposed the actual use case and why it was not possible to use the existing onSuccess and onError callbacks for the purpose. 

Note: In my use case using a global state on the image was perfectly fine as I'm only interested by the last ImageFlow result and not intermediate results.

**Pull request merged**
